#!/bin/bash
# Repository Cleanup Commands for mft-algotrade-bot v2.4.0
# Run these commands to achieve a professional repository structure

echo "=== Repository Cleanup Commands ==="
echo ""
echo "1. REMOVE TEMPORARY FILES & CACHES"
echo "   # Remove Python cache files"
echo "   find . -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true"
echo "   find . -type f -name '*.pyc' -delete"
echo "   find . -type f -name '*.pyo' -delete"
echo "   find . -type f -name '*.pyd' -delete"
echo "   find . -type d -name '.pytest_cache' -exec rm -rf {} +"
echo "   find . -type d -name '.mypy_cache' -exec rm -rf {} +"
echo "   find . -type d -name '.hypothesis' -exec rm -rf {} +"
echo ""
echo "2. CLEAN UP NON-STANDARD FOLDERS (optional)"
echo "   # These folders contain development artifacts - review before deleting"
echo "   # backups/ - contains backup files"
echo "   # reports/ - contains analysis reports"
echo "   # notebooks/ - contains Jupyter notebooks"
echo "   # To remove (if not needed):"
echo "   # rm -rf backups/*"
echo "   # rm -rf reports/*"
echo "   # rm -rf notebooks/*"
echo ""
echo "3. VERIFY CONFIG FILE LOCATIONS"
echo "   # All config files should be in config/ directory"
echo "   echo 'Current config files:'"
echo "   ls -la config/"
echo ""
echo "4. UPDATE GITIGNORE (see new .gitignore file)"
echo "   # Replace existing .gitignore with the updated version"
echo "   cp .gitignore .gitignore.backup"
echo "   # Copy new .gitignore content"
echo ""
echo "5. UPDATE PYPROJECT.TOML (see new pyproject.toml file)"
echo "   # Replace existing pyproject.toml with updated version"
echo "   cp pyproject.toml pyproject.toml.backup"
echo "   # Copy new pyproject.toml content"
echo ""
echo "6. UPDATE MAKEFILE (see new Makefile)"
echo "   # Replace existing Makefile with updated version"
echo "   cp Makefile Makefile.backup"
echo "   # Copy new Makefile content"
echo ""
echo "7. UPDATE README.md"
echo "   # Replace existing README.md with professional version"
echo "   cp README.md README.md.backup"
echo "   # Copy new README.md content"
echo ""
echo "=== Cleanup Complete ==="
echo ""
echo "After applying these changes, run:"
echo "  make install    # Install dependencies"
echo "  make lint       # Check code quality"
echo "  make test       # Run tests"
echo "  make format     # Format code"
